### ISSUE TITLE
db:create fails because of apartment in postgres schemas mode

### ISSUE THREAD

**Issue by AlexanderPavlenko** [influitive/apartment#145]
```
vagrant@vagrant-ubuntu-precise-64:/vagrant$ bin/rake db:create
/usr/local/lib/ruby/gems/2.0.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:891:in `rescue in connect': FATAL:  database "....." does not exist
Run `$ bin/rake db:create db:migrate` to create your database (ActiveRecord::NoDatabaseError)
        from /usr/local/lib/ruby/gems/2.0.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:881:in `connect'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:568:in `initialize'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `new'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `postgresql_connection'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:435:in `new_connection'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:445:in `checkout_new_connection'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `acquire_connection'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
        from /usr/local/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkout'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
        from /usr/local/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activerecord-4.1.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activerecord-4.1.1/lib/active_record/connection_handling.rb:87:in `connection'
        from /usr/local/lib/ruby/gems/2.0.0/gems/apartment-0.24.3/lib/apartment/adapters/postgresql_adapter.rb:76:in `reset'
        from /usr/local/lib/ruby/gems/2.0.0/gems/apartment-0.24.3/lib/apartment/adapters/postgresql_adapter.rb:38:in `initialize'
        from /usr/local/lib/ruby/gems/2.0.0/gems/apartment-0.24.3/lib/apartment/adapters/postgresql_adapter.rb:8:in `new'
        from /usr/local/lib/ruby/gems/2.0.0/gems/apartment-0.24.3/lib/apartment/adapters/postgresql_adapter.rb:8:in `postgresql_adapter'
        from /usr/local/lib/ruby/gems/2.0.0/gems/apartment-0.24.3/lib/apartment/database.rb:47:in `adapter'
        from /usr/local/lib/ruby/gems/2.0.0/gems/apartment-0.24.3/lib/apartment/database.rb:18:in `init'
        from /usr/local/lib/ruby/gems/2.0.0/gems/apartment-0.24.3/lib/apartment/railtie.rb:31:in `block in <class:Railtie>'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:438:in `instance_exec'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:438:in `block in make_lambda'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:184:in `call'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:184:in `block in simple'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:185:in `call'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:185:in `block in simple'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:86:in `call'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:86:in `run_callbacks'
        from /usr/local/lib/ruby/gems/2.0.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
        from /usr/local/lib/ruby/gems/2.0.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
        from /usr/local/lib/ruby/gems/2.0.0/gems/railties-4.1.1/lib/rails/application/finisher.rb:52:in `block in <module:Finisher>'
        from /usr/local/lib/ruby/gems/2.0.0/gems/railties-4.1.1/lib/rails/initializable.rb:30:in `instance_exec'
        from /usr/local/lib/ruby/gems/2.0.0/gems/railties-4.1.1/lib/rails/initializable.rb:30:in `run'
        from /usr/local/lib/ruby/gems/2.0.0/gems/railties-4.1.1/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/local/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
        from /usr/local/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
        from /usr/local/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
        from /usr/local/lib/ruby/2.0.0/tsort.rb:180:in `each'
        from /usr/local/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
        from /usr/local/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
        from /usr/local/lib/ruby/gems/2.0.0/gems/railties-4.1.1/lib/rails/initializable.rb:54:in `run_initializers'
        from /usr/local/lib/ruby/gems/2.0.0/gems/railties-4.1.1/lib/rails/application.rb:288:in `initialize!'
        from /usr/local/lib/ruby/gems/2.0.0/gems/railties-4.1.1/lib/rails/railtie.rb:194:in `public_send'
        from /usr/local/lib/ruby/gems/2.0.0/gems/railties-4.1.1/lib/rails/railtie.rb:194:in `method_missing'
        from /vagrant/config/environment.rb:5:in `<top (required)>'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `block in require'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'
        from /usr/local/lib/ruby/gems/2.0.0/gems/spring-1.1.2/lib/spring/application.rb:92:in `preload'
        from /usr/local/lib/ruby/gems/2.0.0/gems/spring-1.1.2/lib/spring/application.rb:140:in `serve'
        from /usr/local/lib/ruby/gems/2.0.0/gems/spring-1.1.2/lib/spring/application.rb:128:in `block in run'
        from /usr/local/lib/ruby/gems/2.0.0/gems/spring-1.1.2/lib/spring/application.rb:122:in `loop'
        from /usr/local/lib/ruby/gems/2.0.0/gems/spring-1.1.2/lib/spring/application.rb:122:in `run'
        from /usr/local/lib/ruby/gems/2.0.0/gems/spring-1.1.2/lib/spring/application/boot.rb:18:in `<top (required)>'
        from /usr/local/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
```

**Comment by arvindcr** [comment]
This looks like an issue with the springloader in rails trying to initialize the app even during rake db:create
Do bundle exec rake db:create instead so your initialization scripts are not run and don't begin looking for the database before they're created.
