### ISSUE TITLE
Apartment behind HAProxy

### ISSUE THREAD

**Issue by zakirpk** [influitive/apartment#214]
Dear Brad Robertson, I hope you are doing well & would like to thank you for your wonderful apartment gem. I am opening 'Apartment behind HAproxy' issue again as I could not make my application work with apartment gem behind haproxy. I used subdomain elevator as you mentioned in the gem manual. Without HAProxy it is working perfectly. I am facing a lot of Apartment::DatabaseNotFound errors. My application configuration is given below:

************************************ initializers/apartment.rb content ****************************
require 'apartment/elevators/subdomain'
Apartment.configure do |config|
     config.excluded_models = ["StaticPage", "Tenant"]
end
Apartment::Elevators::Subdomain.excluded_subdomains = ['www', 'public']
Rails.application.config.middleware.use 'Apartment::Elevators::Subdomain'

******************************* haproxy contents *********************************

defaults
mode http
log global
option httplog
option dontlognull
option http-server-close
#option forwardfor except 127.0.0.0/8
option redispatch
retries 3
timeout http-request 10s
timeout queue 1m
timeout connect 10s
timeout client 1m
timeout server 1m
timeout http-keep-alive 10s
timeout check 10s
maxconn 128

listen stats 127.2.161.101:8080
mode http
stats enable
stats uri /

listen express 127.2.161.100:8080

cookie GEAR insert indirect nocache
option httpchk GET /
http-check expect rstatus 2..|3..|401

balance leastconn
server local-gear 127.2.161.111:8080 check fall 2 rise 3 inter 2000 cookie local-758437gfgfgdfggdf

Note: This app is hosted on openshift  with auto vertical scale open.
The server 'local-gear' is the gear ( running unit ) and becomes when deployed with name like below:

ex-std-node1.prod
ex-std-node2.prod
ex-std-node3.prod
ex-std-node4.prod
ex-std-node5.prod  etc (These are balanced servers )

********************************* Log file contents ****************************************

I, [2015-01-31T15:13:29.928497 #305602] INFO -- : [ex-std-node11.prod] Started GET "/" for 127.2.161.111at 2015-01-31 15:13:29 -0500
E, [2015-01-31T15:13:29.993063 #305602] ERROR -- : [ex-std-node11.prod] Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-std-node11' at line 1: use ex-std-node11
F, [2015-01-31T15:13:29.996375 #305602] FATAL -- : [ex-std-node11.prod]
Apartment::DatabaseNotFound (Cannot find tenant ex-std-node11):
vendor/bundle/ruby/gems/apartment-0.26.1/lib/apartment/adapters/mysql2_adapter.rb:65:in rescue in connect_to_new' vendor/bundle/ruby/gems/apartment-0.26.1/lib/apartment/adapters/mysql2_adapter.rb:59:inconnect_to_new'

**Comment by desheikh** [comment]
Hi @zakirpk this seems to have been an issue with apartment not escaping database names in mysql. Running your app against the master branch should fix this for you.

**Comment by bradrobertson** [comment]
@zakirpk can you verify that the master branch changes worked? It was a quoting issue it seems.

**Comment by zakirpk** [comment]
Dear @desheikh and @bradrobertson , sorry for too late to answer you people. I tried with master branch. The steps that I followed are below:

1) Added in gemfile
gem 'apartment', :git => 'https://github.com/influitive/apartment.git'

2) initializers/appartment.rb

require 'apartment/elevators/subdomain'
Apartment.configure do |config|
  config.excluded_models = ["StaticPage", "Tenant"]
end
Apartment::Elevators::Subdomain.excluded_subdomains = ['www', 'public', 'admin']
Rails.application.config.middleware.use 'Apartment::Elevators::Subdomain'

Now I am getting these error messages

I, [2015-04-17T03:31:17.312609 #96709]  INFO -- : [ex-std-node4.prod] Started GE
T "/" for 127.3.211.129 at 2015-04-17 03:31:17 -0400
E, [2015-04-17T03:31:17.333652 #96709] ERROR -- : [ex-std-node4.prod] Mysql2::Er
ror: Unknown database 'ex-std-node4': use `ex-std-node4`
F, [2015-04-17T03:31:17.403382 #96709] FATAL -- : [ex-std-node4.prod]
Apartment::TenantNotFound (Cannot find tenant ex-std-node4):
  vendor/bundle/ruby/bundler/gems/apartment-5cfc89ddd515/lib/apartment/adapters/
mysql2_adapter.rb:69:in `rescue in connect_to_new'
  vendor/bundle/ruby/bundler/gems/apartment-5cfc89ddd515/lib/apartment/adapters/
mysql2_adapter.rb:63:in `connect_to_new'
  vendor/bundle/ruby/bundler/gems/apartment-5cfc89ddd515/lib/apartment/adapters/
abstract_adapter.rb:84:in `switch!'
  vendor/bundle/ruby/bundler/gems/apartment-5cfc89ddd515/lib/apartment/elevators
/generic.rb:21:in `call'
  vendor/bundle/ruby/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
  vendor/bundle/ruby/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
  vendor/bundle/ruby/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
  vendor/bundle/ruby/gems/actionpack-4.0.13/lib/action_dispatch/middleware/param
s_parser.rb:27:in `call'
  vendor/bundle/ruby/gems/actionpack-4.0.13/lib/action_dispatch/middleware/flash
.rb:241:in `call'
  vendor/bundle/ruby/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `con
text'
  vendor/bundle/ruby/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `cal
l'
  vendor/bundle/ruby/gems/actionpack-4.0.13/lib/action_dispatch/middleware/cooki
es.rb:486:in `call'
  vendor/bundle/ruby/gems/activerecord-4.0.13/lib/active_record/query_cache.rb:3
6:in `call'
  vendor/bundle/ruby/gems/activerecord-4.0.13/lib/active_record/connection_adapt
ers/abstract/connection_pool.rb:626:in `call'
  vendor/bundle/ruby/gems/actionpack-4.0.13/lib/action_dispatch/middleware/callb
acks.rb:29:in `block in call'
  vendor/bundle/ruby/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:3
73:in `_run__3518408154105171957__call__callbacks'
  vendor/bundle/ruby/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:8
0:in `run_callbacks'
  vendor/bundle/ruby/gems/actionpack-4.0.13/lib/action_dispatch/middleware/callb
acks.rb:27:in `call'
  vendor/bundle/ruby/gems/actionpack-4.0.13/lib/action_dispatch/middleware/remot
e_ip.rb:76:in `call'
  vendor/bundle/ruby/gems/actionpack-4.0.13/lib/action_dispatch/middleware/debug
_exceptions.rb:17:in `call'
  vendor/bundle/ruby/gems/actionpack-4.0.13/lib/action_dispatch/middleware/show_
exceptions.rb:30:in `call'
  vendor/bundle/ruby/gems/railties-4.0.13/lib/rails/rack/logger.rb:38:in `call_a
pp'
  vendor/bundle/ruby/gems/railties-4.0.13/lib/rails/rack/logger.rb:20:in `block
in call'
  vendor/bundle/ruby/gems/activesupport-4.0.13/lib/active_support/tagged_logging
.rb:68:in `block in tagged'
  vendor/bundle/ruby/gems/activesupport-4.0.13/lib/active_support/tagged_logging
.rb:26:in `tagged'
  vendor/bundle/ruby/gems/activesupport-4.0.13/lib/active_support/tagged_logging
.rb:68:in `tagged'
  vendor/bundle/ruby/gems/railties-4.0.13/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/gems/actionpack-4.0.13/lib/action_dispatch/middleware/reque
st_id.rb:21:in `call'
  vendor/bundle/ruby/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/ruby/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/gems/activesupport-4.0.13/lib/active_support/cache/strategy
/local_cache.rb:83:in `call'
  vendor/bundle/ruby/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
  vendor/bundle/ruby/gems/railties-4.0.13/lib/rails/engine.rb:511:in `call'
  vendor/bundle/ruby/gems/railties-4.0.13/lib/rails/application.rb:97:in `call'
  vendor/bundle/ruby/gems/railties-4.0.13/lib/rails/railtie/configurable.rb:30:i
n `method_missing'
  /opt/rh/ruby200/root/usr/share/gems/gems/passenger-4.0.18/lib/phusion_passenge
r/rack/thread_handler_extension.rb:77:in `process_request'
  /opt/rh/ruby200/root/usr/share/gems/gems/passenger-4.0.18/lib/phusion_passenge
r/request_handler/thread_handler.rb:140:in `accept_and_process_next_request'
  /opt/rh/ruby200/root/usr/share/gems/gems/passenger-4.0.18/lib/phusion_passenge
r/request_handler/thread_handler.rb:108:in `main_loop'
  /opt/rh/ruby200/root/usr/share/gems/gems/passenger-4.0.18/lib/phusion_passenge
r/request_handler.rb:441:in `block (3 levels) in start_threads'
