### ISSUE TITLE
Rails 5.0 incompatibilities

### ISSUE THREAD

**Issue by mensfeld** [influitive/apartment#295]
Hey there,

For Rails 5 migrations won't work since the create_table works in a bit different way. If you try to create a tenant you will get following error when loading schema.rb:

```
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown table 'customers': DROP TABLE `customers` CASCADE
```

it happens because AR thinks that this table is already present and tries to remove it before recreation.

It is because of create_table that is here: /activerecord-5.0.0.beta2/lib/active_record/connection_adapters/abstract/schema_statements.rb:275

**Comment by mensfeld** [comment]
temp patch

```
      cust = Root::Customer.create!(
        database: "#{user.id}",
        host: "#{user.id}.#{Settings.urls.host}"
      )
      begin
        Apartment::Tenant.create(cust.database)
      rescue
        system("DB_NAME=#{cust.database} bundle exec rake db:schema:load")
      end
```

middleware and other things seems to work fine once the db has been populated

**Comment by bradrobertson** [comment]
Any chance you'd like to submit a PR to fix?

**Comment by mensfeld** [comment]
@bradrobertson  zero - I'm not familiar with Apartment code :( - I just bypassed this issue. However some inflection stuff inside AR is also broken when doing cross database relations.

**Comment by mensfeld** [comment]
@bradrobertson  are there any plans on providing support for R5?

**Comment by bradrobertson** [comment]
If the community can provide the code, I can provide the merge! It's not a priority for us right now though.

**Comment by dgroulx** [comment]
FWIW I'm using Apartment successfully on Rails 5 with Postgres. Perhaps it's related to the MySQL driver?

**Comment by mensfeld** [comment]
@dgroulx that might be true. Will test it against pg soon!

**Comment by hamdisy** [comment]
Is is works on Rails 5.0 RC1 ?

**Comment by buenaventure** [comment]
This looks similar to #345

**Comment by ball-hayden** [comment]
I'm seeing the following with Rails 5 and MySQL:

```
ActiveRecord::StatementInvalid (Mysql2::Error: MySQL client is not connected: ROLLBACK):
  
mysql2 (0.4.5) lib/mysql2/client.rb:120:in `_query'
mysql2 (0.4.5) lib/mysql2/client.rb:120:in `block in query'
mysql2 (0.4.5) lib/mysql2/client.rb:119:in `handle_interrupt'
mysql2 (0.4.5) lib/mysql2/client.rb:119:in `query'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `block in execute'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `execute'
activerecord (5.0.1) lib/active_record/connection_adapters/mysql/database_statements.rb:31:in `execute'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:242:in `exec_rollback_db_transaction'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract/database_statements.rb:285:in `rollback_db_transaction'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract/query_cache.rb:17:in `rollback_db_transaction'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract/transaction.rb:138:in `rollback'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract/transaction.rb:183:in `rollback_transaction'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract/transaction.rb:204:in `rescue in within_new_transaction'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract/transaction.rb:201:in `within_new_transaction'
activerecord (5.0.1) lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
activerecord (5.0.1) lib/active_record/transactions.rb:211:in `transaction'
activerecord (5.0.1) lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
activerecord (5.0.1) lib/active_record/transactions.rb:319:in `block in save'
activerecord (5.0.1) lib/active_record/transactions.rb:334:in `rollback_active_record_state!'
activerecord (5.0.1) lib/active_record/transactions.rb:318:in `save'
activerecord (5.0.1) lib/active_record/suppressor.rb:41:in `save'
```

When trying to create new records.
