### ISSUE TITLE
Rails 5 association issue - Postgresql

### ISSUE THREAD

**Issue by ronyv89** [influitive/apartment#300]
When defining association like has_many or has_one in Rails 5 and trying to access the associated model object, its throwing this error:

```
NoMethodError - undefined method `_reflect_on_association' for nil:NilClass:
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/table_metadata.rb:47:in `associated_table'
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/relation/predicate_builder.rb:135:in `associated_predicate_builder'
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/relation/predicate_builder.rb:103:in `block in create_binds_for_hash'
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/relation/predicate_builder.rb:100:in `create_binds_for_hash'
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/relation/predicate_builder.rb:103:in `block in create_binds_for_hash'
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/relation/predicate_builder.rb:100:in `create_binds_for_hash'
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/relation/predicate_builder.rb:36:in `create_binds'
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/relation/where_clause_factory.rb:20:in `build'
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/relation/query_methods.rb:626:in `where!'
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/relation/query_methods.rb:619:in `where'
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/associations/association_scope.rb:67:in `last_chain_scope'
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/associations/association_scope.rb:124:in `add_constraints'
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/associations/association_scope.rb:28:in `scope'
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/associations/association_scope.rb:5:in `scope'
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/associations/association.rb:97:in `association_scope'
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/associations/association.rb:86:in `scope'
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/associations/singular_association.rb:44:in `create_scope'
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/associations/association.rb:171:in `initialize_attributes'
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/associations/association.rb:254:in `block in build_record'
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/core.rb:320:in `initialize'
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/inheritance.rb:65:in `new'
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/reflection.rb:152:in `build_association'
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/associations/association.rb:253:in `build_record'
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/associations/singular_association.rb:35:in `build'
   () Users/ronyvarghese/.rvm/gems/ruby-2.2.3@stack_track/bundler/gems/rails-af80974f85f8/activerecord/lib/active_record/associations/builder/singular_association.rb:18:in `build_profile'
```

**Comment by bradrobertson** [comment]
That's odd. We haven't used Apartment with Rails 5, though other people reporting using it. We don't have any specific date for getting it up to date with Rails 5 but if you're able to dig in and find out what's happening, that'd help us a lot get a fix in.

**Comment by SeanRoberts** [comment]
I triggered this same error but it only happened when I moved an existing model into config.excluded_models.  Rails 5 seems to be behaving normally otherwise, and I'm not sure if the error that I triggered was Rails 5 related or just related to the fact that I moved an existing model into excluded_models (perhaps there's a migration or something required that I missed?)

**Comment by SeanRoberts** [comment]
Never mind, I just ran into the same error.  In this case I have two models: +User+, and +UserPermission+.  User is part of <tt>config.excluded_models</tt> and +UserPermission+ is not.  I'll see if I can dig any deeper.

**Comment by bradrobertson** [comment]
Do you have foreign keys between tenanted and non tenanted models? This will likely cause problems.

**Comment by SeanRoberts** [comment]
I do, yes, so maybe Rails 5 is a total red herring here.  Is there a good pattern for managing something like that?  Essentially I have Users, which are global, but I want to create UserPermission records which essentially dictate what a given user is allowed to do on a given tenant.  The goal is to allow a single user to be, for example, the owner of one tenant but just a participant on another.

**Comment by bradrobertson** [comment]
Ya the tenanted => non_tenanted foreign key issue is definitely a thing. There isn't an amazing solution to it other than not specifying the foreign keys in the db and just finding the models yourself rather than using ActiveRecord. It's not *that* big of a pain, but not great.

**Comment by SeanRoberts** [comment]
Works for me, thanks!

**Comment by ronyv89** [comment]
I have 2 excluded models. User and OauthToken. I've defined User has_many OauthToken relationship. This creates a problem. I've another User has_many Project relationship(project is not excluded). This works perfectly

**Comment by bradrobertson** [comment]
Oh that seems different. We definitely have this setup on Rails 4 and it works, so if it's broken having associations between 2 excluded models, then that's a bit different. @ronyv89 any insight you have into this would be helpful in finding a solution.

**Comment by ecdpalma** [comment]
I'm having the same problem as @ronyv89, and after some debug, I've been thinking if it is not related to the way ActiveRecord splits the table name in PredicateBuilder#convert_dot_notation_to_hash.

**Comment by ecdpalma** [comment]
This comment seems to be a hint on understanding the issue: https://github.com/rails/rails/pull/22163#issuecomment-153567249, doesn't it?

**Comment by milep** [comment]
As a temporary workaround I have redefined last_chain_scope method according to
https://github.com/rails/rails/pull/22163/files

```
module ActiveRecord
  module Associations
    class AssociationScope
      private
      def last_chain_scope(scope, table, reflection, owner, association_klass)
        join_keys = reflection.join_keys(association_klass)
        key = join_keys.key
        foreign_key = join_keys.foreign_key

        # we should pass only table name to #where
        table_name = table.name.split(".").last
        value = transform_value(owner[foreign_key])
        scope = scope.where(table_name => { key => value })

        if reflection.type
          polymorphic_type = transform_value(owner.class.base_class.name)
          scope = scope.where(table_name => { reflection.type => polymorphic_type })
        end

        scope
      end
    end
  end
end
``` 

Not sure at all how solid this is.

**Comment by djvs** [comment]
Can confirm this happened immediately from upgrade to Rails 4.2 to Rails 5.0.0.beta3, in an app also using Apartment/Tenant

**Comment by ACPK** [comment]
@djvs - It also happened to me after upgrading to Rails 5.

**Comment by mikecmpbll** [comment]
apparently it was 'mostly' fixed by https://github.com/rails/rails/pull/29058 . can anyone confirm? either way, it's appears to be a rails issue with schema names and joins, so closing for now.
