### ISSUE TITLE
Intermittent Apartment::TenantNotFound error (ActiveRecord::ConnectionNotEstablished)

### ISSUE THREAD

**Issue by stephenchen13** [influitive/apartment#413]
I'm running into an error in my local dev environment in a Rails 5/MySQL application using Unicorn web server where only one out of many sprockets asset requests will 500 from this error: 

```
ActiveRecord::ConnectionNotEstablished (No connection pool with id primary found.):
activerecord (5.0.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `retrieve_connection'
activerecord (5.0.1) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.1) lib/active_record/connection_handling.rb:91:in `connection'
apartment (1.2.0) lib/apartment/adapters/abstract_adapter.rb:58:in `current'
apartment (1.2.0) lib/apartment/adapters/abstract_adapter.rb:104:in `switch'
apartment (1.2.0) lib/apartment/elevators/generic.rb:22:in `call'
rack (2.0.1) lib/rack/etag.rb:25:in `call'
rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.1) lib/rack/head.rb:12:in `call'
rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.0.1) lib/active_record/migration.rb:553:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
web-console (3.4.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.4.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.4.0) lib/web_console/middleware.rb:18:in `catch'
web-console (3.4.0) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:11:in `block in call'
activesupport (5.0.1) lib/active_support/logger_silence.rb:20:in `silence'
activesupport (5.0.1) lib/active_support/logger.rb:63:in `block (3 levels) in broadcast'
activesupport (5.0.1) lib/active_support/logger_silence.rb:20:in `silence'
activesupport (5.0.1) lib/active_support/logger.rb:61:in `block (2 levels) in broadcast'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:11:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
rack-timeout (0.4.2) lib/rack/timeout/core.rb:122:in `block in call'
rack-timeout (0.4.2) lib/rack/timeout/support/timeout.rb:19:in `timeout'
rack-timeout (0.4.2) lib/rack/timeout/core.rb:121:in `call'
activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
sentry-raven (2.3.1) lib/raven/integrations/rack.rb:50:in `call'
railties (5.0.1) lib/rails/engine.rb:522:in `call'
rack (2.0.1) lib/rack/handler/webrick.rb:86:in `service`
```

For example, on a page load that makes the following asset requests:
- `http://woodlawn.lvh.me:3000/assets/application.self-c1e535824912da0de647dc3315ee8469d980bdb5512720cbaefb6d86d99465d4.css?body=1`
- `http://woodlawn.lvh.me:3000/assets/cases.self-a5dd63234a801d9490ef6b45c312a938f17c620e4cdf8b2e2283d3a2accc7fc2.css?body=1`

The request for `application` will 200 while the request for `cases` will 500. However the request for `cases` will 200 if made separately, outside of the context of the page load. This leads me to believe it may be an issue with the database connection pool?

This is my database config:
```
development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  database: [redacted]
```

Would appreciate any help or debugging tips, been banging against this for days now.

**Comment by mikecmpbll** [comment]
thanks for reporting your issue. what elevator are you using and can you provide your apartment config?

**Comment by stephenchen13** [comment]
I'm using the subdomain elevator, here is my config:

```
require 'apartment/elevators/subdomain'

Apartment.configure do |config|
  config.excluded_models = %w{ Tenant }
  config.tenant_names = lambda{ Tenant.pluck(:subdomain) }

  config.use_schemas = false

  config.prepend_environment = !Rails.env.production?
end

Rails.application.config.middleware.insert_before 'Warden::Manager', 'Apartment::Elevators::Subdomain'
Apartment::Elevators::Subdomain.excluded_subdomains = ['www']
```

**Comment by stephenchen13** [comment]
I think the issue may be that each asset request is looking for DB connection and I am running out of connections, or timing out on requests because all connections are tied up. Is there a way to configure Apartment to avoid tenant lookups unnecessarily on asset requests?

**Comment by ocha** [comment]
@mikecmpbll @stephenchen13 I got same error too. I have 50 connections in my DB pool so I doubt if that is causing the issue. I think it is related to multithreaded server. I am running puma with 5 threads, and if I make 2 parallel requests, one of them will get that error.  Is apartments gem threadsafe?

**Comment by mikecmpbll** [comment]
ah, sorry. yeah from your config i can see that you're not using schemas, which means it's switching connection. activerecord connection switching isn't threadsafe (in that way) unfortunately, so with a threaded webserver you will face problems.

as you're using mysql, you can set `use_schemas = true` and you will solve your problems. it's a misleading configuration option name, it should be something like `avoid_switching_connections`. the mysql adapter in "use_schemas mode" will use `use` statements, instead of connection switching, which is threadsafe.

**Comment by ocha** [comment]
Will same solution work with postgresql and puma using databases and not schemes?

**Comment by mikecmpbll** [comment]
@ocha : no. postgres doesn't have a use statement and thus the only way to change database is to reconnect.

**Comment by ocha** [comment]
is there recommended way to use postgres with separate databases with the gem, or that use case is not supported at all? Just having Thread.new{ Apartment::Tenant.switch.... } messes up the connection even in console.

**Comment by mikecmpbll** [comment]
connection-based adapters are supported, but not in a multi-threaded environment. this is due to the way that rails connections are intrinsically linked to the models, meaning that you cannot change the connection for a model in a thread and not change the connection for that model for all threads.

i'm working on a version of apartment now for rails 5.1 which has no threading issues, though.

**Comment by ocha** [comment]
Thank you @mikecmpbll . I am currently testing on Rails 5.1. Let me know if there is anything I can help with.

**Comment by mikecmpbll** [comment]
@ocha thanks, will do 😎

**Comment by rddm2bb** [comment]
@mikecmpbll any update on the status?

**Comment by fuzzygroup** [comment]
I'm also looking for input on this one.  My environment is puma with a separate mysql database per tenant (subdomain elevator) and just as I am about to go into beta, I'm hitting this issue.  Advice on how to move forward would be appreciated.

**Comment by rddm2bb** [comment]
@fuzzygroup you can put puma and sidekiq to only work with 1 thread for now. You can work in cluster mode with booth

**Comment by mikecmpbll** [comment]
@fuzzygroup as explained in this issue, set `config.use_schemas = true` ;)

@rddm2bb my work is at https://github.com/mikecmpbll/apartment/tree/flexible-switching but i've done limited testing with pg

**Comment by rddm2bb** [comment]
@mikecmpbll he uses a separated dabase. schema aproach is a pain in the ass for backups.
If you need something let me know, I have time to work on it. I only use pg so it's ok for me. Maybe I will have some database's as sql server later. Your branch is already working with puma threads?

**Comment by mikecmpbll** [comment]
@rddm2bb mysql doesn't have schemas, but the `use_schemas` option changes the way apartment switches databases with mysql and makes it threadsafe.

feel free to test my branch with pg.

**Comment by balamanoharb** [comment]
I'm also using connection switching as I have different username and password for each database. Because of this I  can't set use_schema=false. 
It throws the same error. 
Did anyone find solution for this issue ?

**Comment by ghost** [comment]
@mikecmpbll any update on a version of apartment which has no threading issues for connection-based adapters ?

**Comment by microspino** [comment]
Hey @mikecmpbll thx for your all work on this. 
Same error here: `ActiveRecord::ConnectionNotEstablished (No connection pool with id primary found.)`

I'm on **RoR 5.0.1, Puma 3.8.2 and apartment 2.1.0**.

If i set Puma **threads_count** to 1, those errors go away.

Is there any chance to know **if/when** https://github.com/mikecmpbll/apartment/tree/flexible-switching  will be merged? 

I saw flexible-switching is a bunch of commits behind apartment. 
Do you plan to update (rebase) it with apartment 2.1.0?

**Comment by mikecmpbll** [comment]
@microspino i don't plan to merge flexible-switching as-is. once the code is stable and my company uses it in production i plan to start a series of smaller MRs to bring the functionality upstream.

**Comment by muyiwaoyeniyi** [comment]
@mikecmpbll Just checking if https://github.com/mikecmpbll/apartment/tree/flexible-switching will be merged? 

Thanks.

**Comment by muyiwaoyeniyi** [comment]
> Will same solution work with postgresql and puma using databases and not schemes?

@ocha What solution did you go with? schemas?

**Comment by iuri-gg** [comment]
I ended up using schemas for pgsql with rails 5.2. However Im in the process of implementing custom solution on top of rails 6 so I can have separate DB per tenant.

**Comment by muyiwaoyeniyi** [comment]
@ocha Ok. Any chance you can share your custom solution as some point?

**Comment by iuri-gg** [comment]
I will try 👍

**Comment by muyiwaoyeniyi** [comment]
Alright. @mikecmpbll Just checking if Rails 6 support will be added. Looks like it has connection switching built in.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Does this issue mean that Apartment is not suited to work fine with puma and multiple puma threads?

**Comment by pramodshinde** [comment]
Any update on this, Can we use https://github.com/mikecmpbll/apartment/tree/flexible-switching in production? @ocha What custom solution you are using, would mind providing some directions?

**Comment by ajaysudhakaranarse** [comment]
We are getting one issue related to the connection pool as `ActiveRecord:: ConnectionNotEstablished (No connection pool with id primary found.)` and our application also running on puma server, When its received continues request it's break due to connection pool error. But when we tried the same with `passenger` server it worked seamlessly.

**Comment by achou** [comment]
```passenger``` is inherently single-threaded, so you won't face the same problems that you had with ```puma```. 
Looks like https://github.com/cpoms/innkeeper is able to solve the issue mentioned above.
