### ISSUE TITLE
Issue when switching adapters from MySQL -> Postgres -> MySQL

### ISSUE THREAD

**Issue by mwalsher** [influitive/apartment#443]
We're migrating from MySQL to Postgres with schemas via Apartment. I'm writing a migration service that will read the data from MySQL and write it to PG.

The gist of the issue is:

Given a model `Account`, which is in Apartment's `excluded_models`:

```
# Connect to MySQL by default
Account.first
# Account Load (2.6ms)  SELECT  `myapp_development`.`accounts`.* FROM `myapp_development`.`accounts`   ORDER BY `myapp_development`.`accounts`.`id` ASC LIMIT 1
# => <Account ...>
# Connect to PG
ActiveRecord::Base.establish_connection(:development_postgres)
Apartment::Tenant.reload!
Apartment::Tenant.init
Account.first
# Account Load (1.3ms)  SELECT  "public"."accounts".* FROM "public"."accounts"   ORDER BY "public"."accounts"."id" ASC LIMIT 1
# => <Account ...>
# Connect back to MySQL
ActiveRecord::Base.establish_connection(:development_mysql)
Apartment::Tenant.reload!
Apartment::Tenant.init
# => Mysql2::Error: Unknown database 'public': SHOW TABLES IN `public` LIKE 'accounts'
# ActiveRecord::StatementInvalid: Mysql2::Error: Unknown database 'public': SHOW TABLES IN `public` LIKE 'accounts'
# from /Users/Walsh/.rvm/gems/ruby-2.0.0-p451@myapp/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `_query'
Account.first
# => Account Load (0.9ms)  SELECT  `public`.`accounts`.* FROM `public`.`accounts`   ORDER BY `public`.`accounts`.`id` ASC LIMIT 1
# Mysql2::Error: Table 'public.accounts' doesn't exist: SELECT  `public`.`accounts`.* FROM `public`.`accounts`   ORDER BY `public`.`accounts`.`id` ASC LIMIT 1
# ActiveRecord::StatementInvalid: Mysql2::Error: Table 'public.accounts' doesn't exist: SELECT  `public`.`accounts`.* FROM `public`.`accounts`   ORDER BY `public`.`accounts`.`id` ASC LIMIT 1
# from /Users/Walsh/.rvm/gems/ruby-2.0.0-p451@myapp/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `_query'
Account.table_name
# => public.accounts
Account.table_name = "myapp_development"
# => Mysql2::Error: Unknown database 'public': SHOW TABLES IN `public` LIKE 'accounts'
# ActiveRecord::StatementInvalid: Mysql2::Error: Unknown database 'public': SHOW TABLES IN `public` LIKE 'accounts'
# from /Users/Walsh/.rvm/gems/ruby-2.0.0-p451@myapp/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `_query'
# Querying non-excluded models works however:
Contact.first
# => <Contact ...>
```

The app is running Ruby 2.0 and Rails 4.1.16. Am I missing something on my end?

**Comment by mikecmpbll** [comment]
when apartment excludes models in "PG schemas mode" it prefixes the model's table_name with the public tenant ("public" schema). seeing as you're switching between adapters it's most likely related to that.

you'll want to do something like what we do in our specs to reset things:

```ruby
Apartment.excluded_models.each do |model|
  klass = model.constantize

  Apartment.connection_class.remove_connection(klass)
  klass.clear_all_connections!
  klass.reset_table_name
end
```

**Comment by mwalsher** [comment]
You're a gentleman and a scholar. Thank you!
