### ISSUE TITLE
Can not run db:migrate, NoMethodError: undefined method `migrate' for ActiveRecord::Migrator

### ISSUE THREAD

**Issue by IngusSkaistkalns** [influitive/apartment#522]
## Steps to reproduce

* Install rails 5.2.0.rc1
* Create tenant
* run db:migrate

## Expected behavior

Migrations are run without errors.

## Actual behavior

Fails with error:
```ruby
NoMethodError: undefined method `migrate' for ActiveRecord::Migrator:Class
.rvm/gems/ruby-2.5.0/gems/apartment-2.1.0/lib/apartment/migrator.rb:13:in `block in migrate'
.rvm/gems/ruby-2.5.0/gems/apartment-2.1.0/lib/apartment/adapters/abstract_adapter.rb:85:in `switch'
.rvm/gems/ruby-2.5.0/gems/apartment-2.1.0/lib/apartment/migrator.rb:10:in `migrate'
.rvm/gems/ruby-2.5.0/gems/apartment-2.1.0/lib/tasks/apartment.rake:36:in `block (3 levels) in <top (required)>'
.rvm/gems/ruby-2.5.0/gems/apartment-2.1.0/lib/tasks/apartment.rake:124:in `block in each_tenant'
.rvm/gems/ruby-2.5.0/gems/parallel-1.12.1/lib/parallel.rb:486:in `call_with_index'
.rvm/gems/ruby-2.5.0/gems/parallel-1.12.1/lib/parallel.rb:318:in `block in work_direct'
.rvm/gems/ruby-2.5.0/gems/parallel-1.12.1/lib/parallel.rb:495:in `with_instrumentation'
.rvm/gems/ruby-2.5.0/gems/parallel-1.12.1/lib/parallel.rb:317:in `work_direct'
.rvm/gems/ruby-2.5.0/gems/parallel-1.12.1/lib/parallel.rb:260:in `map'
.rvm/gems/ruby-2.5.0/gems/parallel-1.12.1/lib/parallel.rb:217:in `each'
.rvm/gems/ruby-2.5.0/gems/apartment-2.1.0/lib/tasks/apartment.rake:123:in `each_tenant'
.rvm/gems/ruby-2.5.0/gems/apartment-2.1.0/lib/tasks/apartment.rake:33:in `block (2 levels) in <top (required)>'
.rvm/gems/ruby-2.5.0/gems/apartment-2.1.0/lib/apartment/tasks/enhancements.rb:44:in `block in enhance_after_task'
.rvm/gems/ruby-2.5.0@global/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => apartment:migrate

```

Now rails have extracted few `ActiveRecord::Migrator` methods into new class `ActiveRecord::MigratorContext`

https://github.com/rails/rails/blob/v5.1.5.rc1/activerecord/lib/active_record/migration.rb#L982
https://github.com/rails/rails/blob/v5.2.0.rc1/activerecord/lib/active_record/migration.rb#L1007

## System configuration

* Database: PostgreSQL 10.1
* Apartment version: 2.1.0
* Apartment config (in `config/initializers/apartment.rb` or so):
  * `use_schemas`: (`true`)
* Rails (or ActiveRecord) version: 5.2.0rc1
* Ruby version: 2.5.0

**Comment by meganemura** [comment]
Close in favor of #523.
