### ISSUE TITLE
PG::UndefinedFunction: ERROR:  function pg_stat_statements_reset() does not exist

### ISSUE THREAD

**Issue by shivabhusal** [influitive/apartment#578]
## Error
```ruby
 > Apartment::Tenant.create 'new1'
---------------------------
   (4.3ms)  CREATE SCHEMA "new1"
   (4.3ms)  CREATE SCHEMA "new1"
  SQL (6.8ms)  CREATE EXTENSION IF NOT EXISTS "plpgsql"
  SQL (6.8ms)  CREATE EXTENSION IF NOT EXISTS "plpgsql"
  SQL (4.1ms)  CREATE EXTENSION IF NOT EXISTS "pg_stat_statements"
  SQL (4.1ms)  CREATE EXTENSION IF NOT EXISTS "pg_stat_statements"
PG::UndefinedFunction: ERROR:  function pg_stat_statements_reset() does not exist
: CREATE EXTENSION IF NOT EXISTS "pg_stat_statements"
PG::UndefinedFunction: ERROR:  function pg_stat_statements_reset() does not exist
: CREATE EXTENSION IF NOT EXISTS "pg_stat_statements"
ActiveRecord::StatementInvalid: PG::UndefinedFunction: ERROR:  function pg_stat_statements_reset() does not exist
: CREATE EXTENSION IF NOT EXISTS "pg_stat_statements"
	from /app/vendor/bundle/ruby/2.2.0/bundler/gems/rails-c0e1e4a069b3/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:596:in `async_exec'
	from /app/vendor/bundle/ruby/2.2.0/bundler/gems/rails-c0e1e4a069b3/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:596:in `block in exec_no_cache'
	from /app/vendor/bundle/ruby/2.2.0/bundler/gems/rails-c0e1e4a069b3/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
	from /app/vendor/bundle/ruby/2.2.0/bundler/gems/rails-c0e1e4a069b3/activesupport/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /app/vendor/bundle/ruby/2.2.0/bundler/gems/rails-c0e1e4a069b3/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
	from /app/vendor/bundle/ruby/2.2.0/bundler/gems/rails-c0e1e4a069b3/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:596:in `exec_no_cache'
	from /app/vendor/bundle/ruby/2.2.0/bundler/gems/rails-c0e1e4a069b3/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:588:in `execute_and_clear'
	from /app/vendor/bundle/ruby/2.2.0/bundler/gems/rails-c0e1e4a069b3/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
	from /app/vendor/bundle/ruby/2.2.0/bundler/gems/rails-c0e1e4a069b3/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:342:in `enable_extension'
	from /app/vendor/bundle/ruby/
```
## Expected behavior
Should have created the schema and have done migrations.

## Actual behavior
this error is not letting me do anything
## System configuration

* Database: (Tell us what database and its version you use.)
`psql (PostgreSQL) 11.1 (Ubuntu 11.1-1.pgdg16.04+1)`
* Apartment version:
` (2.2.0)`

* Apartment config (in `config/initializers/apartment.rb` or so):

  * `use_schemas`: (`true`)

* Rails (or ActiveRecord) version:
`2.4.2`
* Ruby version:
`2.2.3`

**Comment by cleicar** [comment]
Hi! Do we have any news about this issue? 

@shivabhusal was you able to fix it?

**Comment by bipashant** [comment]
@shivabhusal 
https://stackoverflow.com/questions/28452481/heroku-apartment-pgerror-error-function-pg-stat-statements-reset-does-no

**Comment by mikecmpbll** [comment]
i'll assume a heroku issue unless confirmed otherwise.
